//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndigoSoft.Reports.Fixa.DataBase
{
    using System;
    
    public partial class BaseCompleta
    {
        public int int_Id { get; set; }
        public string int_Tabulacao { get; set; }
        public Nullable<bool> int_Normativo { get; set; }
        public string int_CodigoNormativo { get; set; }
        public string int_NormativoSiebel { get; set; }
        public string int_TipoLigacao { get; set; }
        public Nullable<bool> int_ClienteBase { get; set; }
        public Nullable<bool> int_PreCadastro { get; set; }
        public Nullable<bool> int_AtualizacaoReceita { get; set; }
        public string int_CPF { get; set; }
        public string int_NomeCompleto { get; set; }
        public string int_NomeMae { get; set; }
        public Nullable<System.DateTime> int_DataNascimento { get; set; }
        public string int_TelefoneResidencial { get; set; }
        public string int_TelefoneCelular { get; set; }
        public string int_TelefoneComercial { get; set; }
        public string int_Email { get; set; }
        public Nullable<bool> int_DesejaSMS { get; set; }
        public string int_CEP { get; set; }
        public string int_Logradouro { get; set; }
        public string int_Estado { get; set; }
        public string int_Cidade { get; set; }
        public string int_Bairro { get; set; }
        public string int_Intervalo { get; set; }
        public string int_Numero { get; set; }
        public string int_TipoComplemento1 { get; set; }
        public string int_Complemento1 { get; set; }
        public string int_TipoComplemento2 { get; set; }
        public string int_Complemento2 { get; set; }
        public string int_TipoComplemento3 { get; set; }
        public string int_Complemento3 { get; set; }
        public string int_Transversal1 { get; set; }
        public string int_Transversal2 { get; set; }
        public string int_CEPCobranca { get; set; }
        public string int_LogradouroCobranca { get; set; }
        public string int_EstadoCobranca { get; set; }
        public string int_CidadeCobranca { get; set; }
        public string int_BairroCobranca { get; set; }
        public string int_NumeroCobranca { get; set; }
        public string int_TipoComplemento1Cobranca { get; set; }
        public string int_Complemento1Cobranca { get; set; }
        public string int_TipoComplemento2Cobranca { get; set; }
        public string int_Complemento2Cobranca { get; set; }
        public string int_TipoComplemento3Cobranca { get; set; }
        public string int_Complemento3Cobranca { get; set; }
        public Nullable<bool> int_LiberacaoOpp { get; set; }
        public string int_DadosDaPlaca { get; set; }
        public string int_DadosDaCobertura { get; set; }
        public string int_TelevisaoDisponivel { get; set; }
        public string int_TelefoneDisponivel { get; set; }
        public string int_InternetDisponivel { get; set; }
        public string int_TelevisaoAdiquirida { get; set; }
        public string int_TelefoneAdiquirida { get; set; }
        public string int_InternetAdiquirida { get; set; }
        public string int_AdicionaisAduidida { get; set; }
        public string int_ErroDescricao { get; set; }
        public Nullable<bool> int_DisponibilidadeData { get; set; }
        public string int_DataAgendamento { get; set; }
        public string int_LoginUsuario { get; set; }
        public Nullable<int> int_TMAResumo { get; set; }
        public Nullable<int> int_TMAHumano { get; set; }
        public Nullable<int> int_TMARobo { get; set; }
        public Nullable<int> int_TMAGeral { get; set; }
        public string int_DataHora { get; set; }
        public string int_StatusPlaca { get; set; }
        public string int_Armario { get; set; }
        public string int_ClasseDoArmario { get; set; }
        public Nullable<int> int_CtrOutraChance { get; set; }
        public Nullable<int> int_PontuacaoTelefone { get; set; }
        public Nullable<int> int_PontuacaoInternet { get; set; }
        public Nullable<int> int_PontuacaoTV { get; set; }
        public Nullable<int> int_PontuacaoTotal { get; set; }
        public Nullable<int> int_QtdeProdutosDisponiveis { get; set; }
        public string int_GrauMaxInternet { get; set; }
        public string int_GrauMaxTV { get; set; }
        public string int_IntencaoInternet { get; set; }
        public string int_IntencaoTelefone { get; set; }
        public string int_IntencaoTV { get; set; }
        public string int_AceiteOfertaMovel { get; set; }
        public string int_RecusaTelevisao { get; set; }
        public string int_RecusaCelular { get; set; }
        public string int_RecusaInternet { get; set; }
        public string int_RecusaTelefone { get; set; }
        public string int_Sexo { get; set; }
        public Nullable<bool> int_TransferenciaMovel { get; set; }
        public string int_TabelaPreco { get; set; }
        public string int_GrupoPreco { get; set; }
        public string int_CategoriaOferta { get; set; }
        public string int_Ofertas { get; set; }
        public string int_GrupoPromocao { get; set; }
        public string int_Promocao { get; set; }
    }
}
