//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndigoSoft.Reports.Fixa.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class indigo_TabuladorInteracao
    {
        public int iti_id { get; set; }
        public string iti_loginOperador { get; set; }
        public Nullable<System.DateTime> iti_dataOcorrencia { get; set; }
        public string iti_NomeCliente { get; set; }
        public string iti_TelefoneResidencial { get; set; }
        public string iti_TelefoneComercial { get; set; }
        public string iti_TelefoneCelular { get; set; }
        public string iti_Endereco { get; set; }
        public Nullable<System.DateTime> iti_DataTabulada { get; set; }
        public string iti_RecusaBanda { get; set; }
        public string iti_RecusaTV { get; set; }
        public string iti_VendaTabulacao { get; set; }
        public string iti_Inapta { get; set; }
        public string iti_Improdutiva { get; set; }
        public string iti_Documento { get; set; }
        public string iti_TipoObservacao { get; set; }
        public string iti_TipoOportunidade { get; set; }
        public string iti_ProdutosAdicionais { get; set; }
        public string iti_RecusaLinha { get; set; }
        public string iti_GrupoAtendimento { get; set; }
        public string iti_DataNascimento { get; set; }
        public string iti_Email { get; set; }
        public string iti_bairro { get; set; }
        public string iti_CEP { get; set; }
        public string iti_Cidade { get; set; }
        public string iti_Complemento { get; set; }
        public string iti_NumeroLogradouro { get; set; }
        public string iti_uf { get; set; }
        public string iti_LinhaAdquirida { get; set; }
        public string iti_BandaLargaAdquirida { get; set; }
        public string iti_TVAdquirida { get; set; }
        public string iti_MovelAdquirido { get; set; }
    }
}
