//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndigoSoft.Reports.Fixa.DataBase.DataModel
{
    using System;
    
    public partial class ExportarPipeline
    {
        public int Id { get; set; }
        public string Origem { get; set; }
        public string Cliente { get; set; }
        public string Projeto { get; set; }
        public string Produto { get; set; }
        public string Status_Edita { get; set; }
        public string Tipo_Edita { get; set; }
        public string Previsão_Edita { get; set; }
        public Nullable<decimal> Licença_Edita { get; set; }
        public Nullable<int> Quantidade_Edita { get; set; }
        public Nullable<decimal> Total_Edita { get; set; }
        public string Observação_Edita { get; set; }
    }
}
