//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndigoSoft.Reports.Fixa.DataBase.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indigo_LogControleCusto
    {
        public int lcc_Id { get; set; }
        public Nullable<int> lcc_IcoId { get; set; }
        public Nullable<System.DateTime> lcc_DataHora { get; set; }
        public string lcc_Mensagem { get; set; }
    
        public virtual Indigo_ConfiguracaoControleCusto Indigo_ConfiguracaoControleCusto { get; set; }
    }
}
