//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndigoSoft.Reports.Fixa.DataBase.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indigo_Produto
    {
        public Indigo_Produto()
        {
            this.Indigo_Licencas = new HashSet<Indigo_Licencas>();
            this.Indigo_Projeto = new HashSet<Indigo_Projeto>();
            this.Indigo_Pipeline = new HashSet<Indigo_Pipeline>();
        }
    
        public int prd_Id { get; set; }
        public Nullable<int> prd_ClfId { get; set; }
        public string prd_Descricao { get; set; }
        public string prd_Sigla { get; set; }
        public Nullable<int> prd_ativo { get; set; }
    
        public virtual Indigo_ClienteFinal Indigo_ClienteFinal { get; set; }
        public virtual ICollection<Indigo_Licencas> Indigo_Licencas { get; set; }
        public virtual ICollection<Indigo_Projeto> Indigo_Projeto { get; set; }
        public virtual ICollection<Indigo_Pipeline> Indigo_Pipeline { get; set; }
    }
}
