//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndigoSoft.Reports.Fixa.DataBase.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indigo_Contratante
    {
        public Indigo_Contratante()
        {
            this.Indigo_Filial = new HashSet<Indigo_Filial>();
        }
    
        public int con_Id { get; set; }
        public string con_Nome { get; set; }
        public string con_CNPJ { get; set; }
        public string con_Responsavel { get; set; }
        public string con_Telefone { get; set; }
        public string con_Email { get; set; }
        public string con_Sigla { get; set; }
    
        public virtual ICollection<Indigo_Filial> Indigo_Filial { get; set; }
    }
}
