//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndigoSoft.Reports.Fixa.DataBase.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indigo_TelasUsuario
    {
        public int tuo_Id { get; set; }
        public Nullable<int> tuo_TelId { get; set; }
        public Nullable<int> tuo_UsrId { get; set; }
    
        public virtual Indigo_Telas Indigo_Telas { get; set; }
        public virtual Indigo_Usuario Indigo_Usuario { get; set; }
    }
}
