//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndigoSoft.Reports.Fixa.DataBase.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indigo_Licencas
    {
        public Indigo_Licencas()
        {
            this.Indigo_ControleLogin = new HashSet<Indigo_ControleLogin>();
            this.Indigo_NotaFiscal = new HashSet<Indigo_NotaFiscal>();
            this.Indigo_ConfiguracaoControleCusto = new HashSet<Indigo_ConfiguracaoControleCusto>();
            this.Indigo_ControleCusto = new HashSet<Indigo_ControleCusto>();
        }
    
        public System.Guid lic_Id { get; set; }
        public Nullable<int> lic_FilId { get; set; }
        public Nullable<int> lic_PrdId { get; set; }
        public string lic_Contrato { get; set; }
        public Nullable<int> lic_Qtde { get; set; }
        public Nullable<System.DateTime> lic_DataContratacao { get; set; }
        public Nullable<System.DateTime> lic_ValidadeLicenca { get; set; }
    
        public virtual ICollection<Indigo_ControleLogin> Indigo_ControleLogin { get; set; }
        public virtual Indigo_Filial Indigo_Filial { get; set; }
        public virtual Indigo_Produto Indigo_Produto { get; set; }
        public virtual ICollection<Indigo_NotaFiscal> Indigo_NotaFiscal { get; set; }
        public virtual ICollection<Indigo_ConfiguracaoControleCusto> Indigo_ConfiguracaoControleCusto { get; set; }
        public virtual ICollection<Indigo_ControleCusto> Indigo_ControleCusto { get; set; }
    }
}
