//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndigoSoft.Reports.Fixa.DataBase.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indigo_NotaFiscal
    {
        public int ntf_id { get; set; }
        public Nullable<System.Guid> ntf_LicId { get; set; }
        public string ntf_NumeroNotaFiscal { get; set; }
        public Nullable<System.DateTime> ntf_DataEmissao { get; set; }
        public Nullable<decimal> ntf_Valor { get; set; }
    
        public virtual Indigo_Licencas Indigo_Licencas { get; set; }
    }
}
