//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndigoSoft.Reports.Fixa.DataBase.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indigo_UtilizacaoPa
    {
        public int uta_Id { get; set; }
        public Nullable<int> uta_PrdId { get; set; }
        public string uta_IdAgente { get; set; }
        public string uta_NomaAgente { get; set; }
        public Nullable<System.DateTime> uta_DataUtilizacao { get; set; }
    }
}
