//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndigoSoft.Reports.Fixa.DataBase.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indigo_ControleCusto
    {
        public int icc_Id { get; set; }
        public Nullable<System.Guid> icc_LicId { get; set; }
        public Nullable<System.DateTime> icc_DataAtendimento { get; set; }
        public string icc_IdOperador { get; set; }
        public string icc_NomeOperador { get; set; }
    
        public virtual Indigo_Licencas Indigo_Licencas { get; set; }
    }
}
