//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndigoSoft.Reports.Fixa.DataBase.DataModel
{
    using System;
    
    public partial class ListaJustifica
    {
        public string Cliente { get; set; }
        public string Produto { get; set; }
        public string Projeto { get; set; }
        public string Fase { get; set; }
        public string Atividade { get; set; }
        public System.DateTime DataInicio { get; set; }
        public System.DateTime DataFim { get; set; }
        public string Aprovacao { get; set; }
        public string Motivo { get; set; }
    }
}
